version: '3.4'

services:
  cthulhu.service:
    restart: always
    container_name : cthulhu_service
    image: cthulhu_service
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Cthulhu.Service/Dockerfile