version: '3.4'

services:
  testsite:
    ports:
      - 8080:80
    image: ${DOCKER_REGISTRY}testsite
    restart: always
    container_name: test_site
    build:
      context: .
      dockerfile: TestSite/Dockerfile

  cthulhu.service:
    image: ${DOCKER_REGISTRY}cthulhuservice
    restart: always
    container_name: Cthulhu.Service
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Cthulhu.Service/Dockerfile

  mongo:
    container_name: MongoDB
    hostname: ${MONGO_DB_HOST}
    image: mongo
    restart: always
    ports:
      - ${MONGO_DB_EXTERNAL_PORT}:${MONGO_DB_INTERNAL_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}

