version: '3.4'

services:
  cthulhu.service:
    hostname: cthulhu_service
    restart: always
    container_name : cthulhu_service
    image: cthulhu_service
    ports:
      - 127.0.0.1:5000:80
    build:
      context: .
      dockerfile: Cthulhu.Service/Dockerfile

  cthulhu.web:
    hostname: cthulhu_web
    restart: always
    container_name : cthulhu_web
    image: cthulhu_web
    ports:
      - 127.0.0.1:5001:80
    build:
      context: Cthulhu.WebUI
      dockerfile: Dockerfile