name: build and deploy

on:
  push:
    branches: [ main_old ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Cthulhu.WebUI/Dockerfile
          tags: vladzvx/cthulhu_online:webui
          
  deploy_compose:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        password  : ${{ secrets.PROD_PWD }}
        port: 22
        script: |
          cd /bin
          echo "${{ secrets.PROD_ENV }}"> env_file
          rm -r cthulhu-online
          git clone https://${{ secrets.GH_PWD }}@github.com/vladzvx/cthulhu-online
          chmod u+x cthulhu-online
          mv env_file cthulhu-online/.env
          cd cthulhu-online
          docker-compose up -d --build
